<a href="https://colab.research.google.com/github/RAGISHIVANAND/DEEP_LEARNING/blob/main/Tensorflow_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
helloworld = tf.constant("hello,TensorFlow")
print("Tensor:",helloworld)
print("value:",helloworld.numpy())


Tensor: tf.Tensor(b'hello,TensorFlow', shape=(), dtype=string)
value: b'hello,TensorFlow'


In [ ]:
a = tf.ones([2,3])
print(a)
a = tf.Variable(a)
a[0,0].assign(10)
b=a.read_value()
print(b)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[10.  1.  1.]
 [ 1.  1.  1.]], shape=(2, 3), dtype=float32)


In [ ]:
###===ADD,MULTIPLY,DIV.ETC===#
a=tf.constant(2)
b=tf.constant(3)
print("a+b:",a.numpy()+b.numpy())
print("Addition with constants:",a+b)
print("Addition with constants:",tf.add(a,b))
print("a*b:",a.numpy()*b.numpy())
print("Multiplication with constants:",a*b)
print("Multiplication with constants:",tf.multiply(a,b))
matrix1 = tf.constant([[3.,3.]])




##===create another constant that produces a 2×1 matrix
matrix2 = tf.constant([[2.],[2.]])
product =tf.matmul(matrix1,matrix2)
print("Multiplication with matrixes:",product)
print("broadcast matrix in Multiplication:",matrix1*matrix2)


##==cast operations==#
a = tf.convert_to_tensor(2.)
b= tf.cast (a,tf.int32)
print(a,b)

##==shape operations==##
a = tf.ones([2,3])
print(a.shape[0],a.shape[1]) #2,3
shape = tf.shape(a)          #a tensor
print(shape[0],shape[1])

a+b: 5
Addition with constants: tf.Tensor(5, shape=(), dtype=int32)
Addition with constants: tf.Tensor(5, shape=(), dtype=int32)
a*b: 6
Multiplication with constants: tf.Tensor(6, shape=(), dtype=int32)
Multiplication with constants: tf.Tensor(6, shape=(), dtype=int32)
Multiplication with matrixes: tf.Tensor([[12.]], shape=(1, 1), dtype=float32)
broadcast matrix in Multiplication: tf.Tensor(
[[6. 6.]
 [6. 6.]], shape=(2, 2), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32) tf.Tensor(2, shape=(), dtype=int32)
2 3
tf.Tensor(2, shape=(), dtype=int32) tf.Tensor(3, shape=(), dtype=int32)
